# Generated by Django 5.1.15 on 2026-09-12 16:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelregistry', '0002_vulnerabilityset_imt_representation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frozen_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('country_code', models.CharField(db_index=True, max_length=2)),
                ('version', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=200)),
                ('source_model', models.CharField(help_text='The seismic source model, such as GEM Global Hazard Mosaic v2023.', max_length=200)),
                ('source_model_checksum', models.CharField(blank=True, max_length=64)),
                ('ground_motion_models', models.JSONField(default=list, help_text='The GMPEs the logic tree used.')),
                ('licence', models.CharField(blank=True, max_length=120)),
                ('licence_cleared', models.BooleanField(default=False)),
                ('licence_note', models.TextField(blank=True)),
                ('engine_version', models.CharField(blank=True, max_length=32)),
                ('calculation_checksum', models.CharField(blank=True, max_length=64)),
                ('job_checksum', models.CharField(blank=True, max_length=64)),
                ('investigation_time', models.FloatField(default=0.0)),
                ('stochastic_event_sets', models.IntegerField(default=0)),
                ('event_count', models.IntegerField(default=0)),
                ('cell_count', models.IntegerField(default=0)),
                ('footprint_row_count', models.BigIntegerField(default=0)),
                ('imts', models.JSONField(default=list, help_text='Intensity measures this hazard set carries.')),
                ('samples_above_range', models.BigIntegerField(default=0)),
                ('conversion_report', models.JSONField(default=dict)),
                ('publication_state', models.CharField(choices=[('draft', 'Draft'), ('candidate', 'Candidate awaiting approval'), ('approved', 'Approved'), ('published', 'Published'), ('superseded', 'Superseded'), ('withdrawn', 'Withdrawn')], default='draft', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hazard_sets', to='modelregistry.areaperilgrid')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['country_code', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='modelversion',
            name='hazard_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='models', to='modelregistry.hazardset'),
        ),
        migrations.AddConstraint(
            model_name='hazardset',
            constraint=models.UniqueConstraint(fields=('country_code', 'version'), name='unique_hazard_version'),
        ),
    ]
