# Generated by Django 5.1.15 on 2026-09-12 18:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelregistry', '0003_hazardset_modelversion_hazard_set_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frozen_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('country_code', models.CharField(db_index=True, max_length=2)),
                ('version', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=200)),
                ('source_organisation', models.CharField(blank=True, max_length=200)),
                ('publication_reference', models.CharField(blank=True, max_length=300)),
                ('licence', models.CharField(blank=True, max_length=120)),
                ('licence_cleared', models.BooleanField(default=False)),
                ('licence_note', models.TextField(blank=True)),
                ('archive_checksum', models.CharField(blank=True, max_length=64)),
                ('archive_bytes', models.BigIntegerField(default=0)),
                ('file_manifest', models.JSONField(default=list, help_text='Every file in the package, with its size and checksum.')),
                ('job_configuration', models.JSONField(default=dict)),
                ('published_calculation_mode', models.CharField(blank=True, max_length=32)),
                ('intensity_measures', models.JSONField(default=list)),
                ('tectonic_regions', models.JSONField(default=list)),
                ('estimated_realizations', models.IntegerField(default=0)),
                ('logic_tree_summary', models.JSONField(default=dict)),
                ('publication_state', models.CharField(choices=[('draft', 'Draft'), ('candidate', 'Candidate awaiting approval'), ('approved', 'Approved'), ('published', 'Published'), ('superseded', 'Superseded'), ('withdrawn', 'Withdrawn')], default='draft', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['country_code', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HazardJobSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('overrides', models.JSONField(default=dict)),
                ('resolved_configuration', models.JSONField(default=dict)),
                ('conversion_report', models.JSONField(default=dict)),
                ('site_join_report', models.JSONField(default=dict)),
                ('problems', models.JSONField(default=list)),
                ('is_runnable', models.BooleanField(default=False)),
                ('job_checksum', models.CharField(blank=True, max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hazard_job_specs', to='modelregistry.areaperilgrid')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_specs', to='modelregistry.hazardmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='hazardmodel',
            constraint=models.UniqueConstraint(fields=('country_code', 'version'), name='unique_hazard_model_version'),
        ),
    ]
