# Generated by Django 5.1.15 on 2026-09-13 18:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelregistry', '0007_vulnerabilityset_assumption_variants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionTolerances',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frozen_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=200)),
                ('source', models.CharField(blank=True, help_text='The study, standard or judgement these tolerances come from.', max_length=300)),
                ('values', models.JSONField(default=dict, help_text="Tolerance by check name, as the converter's QA module names them.")),
                ('publication_state', models.CharField(choices=[('draft', 'Draft'), ('candidate', 'Candidate awaiting approval'), ('approved', 'Approved'), ('published', 'Published'), ('superseded', 'Superseded'), ('withdrawn', 'Withdrawn')], default='draft', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversion_tolerances_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'conversion tolerances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HazardBenchmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frozen_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('country_code', models.CharField(db_index=True, max_length=2)),
                ('label', models.CharField(max_length=200)),
                ('source', models.CharField(help_text='The published study these curves come from, with its edition.', max_length=300)),
                ('reference', models.CharField(blank=True, help_text='Where a reviewer can check it.', max_length=300)),
                ('points', models.JSONField(default=list, help_text='Each point as areaperil_id, imt, return_period and intensity, in the units the measure is stated in.')),
                ('tolerance', models.DecimalField(blank=True, decimal_places=4, help_text='Permitted proportional difference. Null until somebody has decided one, and a comparison without it decides nothing.', max_digits=6, null=True)),
                ('publication_state', models.CharField(choices=[('draft', 'Draft'), ('candidate', 'Candidate awaiting approval'), ('approved', 'Approved'), ('published', 'Published'), ('superseded', 'Superseded'), ('withdrawn', 'Withdrawn')], default='draft', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazard_benchmarks_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('grid', models.ForeignKey(blank=True, help_text='The grid whose cells the points are stated against.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='benchmarks', to='modelregistry.areaperilgrid')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['country_code', '-created_at'],
            },
        ),
    ]
