# Generated by Django 5.1.15 on 2026-09-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelregistry', '0013_alter_vulnerabilityset_imt_representation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardset',
            name='logic_tree_paths',
            field=models.IntegerField(default=1, help_text='Logic-tree paths this event set pools. Each is an alternative scientific view of the hazard, and the years run across all of them.'),
        ),
    ]
