# Generated by Django 5.1.15 on 2026-09-11 00:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('exposure', '0001_initial'),
        ('modelregistry', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('hazard', 'Hazard run'), ('conversion', 'Conversion run'), ('analysis', 'Analysis run')], db_index=True, max_length=16)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('running', 'Running'), ('blocked', 'Blocked'), ('cancelling', 'Cancelling'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('succeeded', 'Succeeded')], db_index=True, default='draft', max_length=16)),
                ('stage', models.CharField(blank=True, help_text='Current pipeline stage key.', max_length=32)),
                ('progress', models.FloatField(default=0.0)),
                ('execution_profile', models.CharField(default='standard', help_text='Declared CPU, memory and timeout envelope from section 11.', max_length=32)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('failure_stage', models.CharField(blank=True, max_length=32)),
                ('failure_summary', models.CharField(blank=True, max_length=500)),
                ('failure_detail', models.TextField(blank=True)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('settings_hash', models.CharField(blank=True, max_length=80)),
                ('peak_memory_mb', models.IntegerField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Null for model-build runs, which belong to a model version rather than a project.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='projects.project')),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='runs.run')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HazardRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('openquake_calculation_id', models.CharField(blank=True, max_length=32)),
                ('openquake_version', models.CharField(blank=True, max_length=32)),
                ('image_digest', models.CharField(blank=True, max_length=120)),
                ('job_settings', models.JSONField(blank=True, default=dict)),
                ('imts', models.JSONField(blank=True, default=list)),
                ('investigation_time', models.FloatField(blank=True, null=True)),
                ('stochastic_event_sets', models.IntegerField(blank=True, null=True)),
                ('random_seed', models.BigIntegerField(blank=True, help_text='Recorded so a reproducible run can be repeated exactly.', null=True)),
                ('event_count', models.BigIntegerField(blank=True, null=True)),
                ('site_count', models.BigIntegerField(blank=True, null=True)),
                ('gmf_bytes', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hazard_runs', to='modelregistry.areaperilgrid')),
                ('model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hazard_runs', to='modelregistry.modelversion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hazard', to='runs.run')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConversionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converter_version', models.CharField(blank=True, max_length=32)),
                ('event_policy', models.CharField(blank=True, help_text='The approved event identity specification applied.', max_length=64)),
                ('occurrence_policy', models.CharField(blank=True, max_length=64)),
                ('intensity_bin_set', models.CharField(blank=True, max_length=64)),
                ('source_checksum', models.CharField(blank=True, max_length=80)),
                ('target_checksum', models.CharField(blank=True, max_length=80)),
                ('qa_state', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('waived', 'Waived with rationale')], default='pending', max_length=16)),
                ('qa_report', models.JSONField(blank=True, default=dict)),
                ('frequency_preserved', models.BooleanField(blank=True, null=True)),
                ('checkpoint', models.JSONField(blank=True, default=dict, help_text='Durable restart point, so a long conversion can resume without republishing.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversion_runs', to='modelregistry.modelversion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('hazard_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions', to='runs.hazardrun')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversion', to='runs.run')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('perspectives', models.JSONField(default=list, help_text='Requested perspectives, checked against the source data.')),
                ('analysis_settings', models.JSONField(blank=True, default=dict)),
                ('run_currency', models.CharField(blank=True, max_length=3)),
                ('oasis_analysis_id', models.CharField(blank=True, max_length=32)),
                ('oasis_portfolio_id', models.CharField(blank=True, max_length=32)),
                ('keys_summary', models.JSONField(blank=True, default=dict)),
                ('keys_reconciled', models.BooleanField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('enrichment_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analysis_runs', to='exposure.enrichmentrun')),
                ('exception_approval', models.ForeignKey(blank=True, help_text='The approval that permitted an unreconciled or exceptional run to proceed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_runs', to='audit.approval')),
                ('exposure_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_runs', to='exposure.exposureversion')),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_runs', to='modelregistry.modelversion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='runs.run')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RunStageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(blank=True, max_length=32)),
                ('state', models.CharField(max_length=16)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Throughput, memory and I/O measurements captured at this stage.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='runs.run')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['project', 'state', '-created_at'], name='runs_run_project_6d9f39_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['kind', 'state'], name='runs_run_kind_27aaa4_idx'),
        ),
        migrations.AddIndex(
            model_name='runstageevent',
            index=models.Index(fields=['run', 'created_at'], name='runs_runsta_run_id_041a5c_idx'),
        ),
    ]
