# Generated by Django 5.1.15 on 2026-09-11 00:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uri', models.CharField(max_length=1100, unique=True)),
                ('checksum', models.CharField(blank=True, help_text='Algorithm-prefixed content digest, recorded at registration.', max_length=80)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('content_type', models.CharField(default='application/octet-stream', max_length=160)),
                ('retention', models.CharField(choices=[('permanent', 'Permanent'), ('model_asset', 'Model Asset'), ('hazard_intermediate', 'Hazard Intermediate'), ('portfolio', 'Portfolio'), ('result', 'Result'), ('diagnostic', 'Diagnostic'), ('operational', 'Operational')], max_length=32)),
                ('access', models.CharField(choices=[('project', 'Project'), ('model', 'Model'), ('platform', 'Platform')], default='project', max_length=16)),
                ('state', models.CharField(choices=[('pending', 'Awaiting upload'), ('registered', 'Registered'), ('quarantined', 'Quarantined'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('role', models.CharField(blank=True, help_text='What this artifact is in its manifest, such as oed_location or footprint.', max_length=64)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('validation_note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtifactLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_type', models.CharField(help_text='The kind of record, such as exposure_version, hazard_run or result_set.', max_length=64)),
                ('subject_id', models.UUIDField()),
                ('role', models.CharField(max_length=64)),
                ('direction', models.CharField(choices=[('input', 'Input'), ('output', 'Output')], default='output', max_length=8)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='artifacts.artifact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['project', 'role'], name='artifacts_a_project_f3024e_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['state', 'expires_at'], name='artifacts_a_state_c3161e_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['checksum'], name='artifacts_a_checksu_e32e45_idx'),
        ),
        migrations.AddIndex(
            model_name='artifactlink',
            index=models.Index(fields=['subject_type', 'subject_id'], name='artifacts_a_subject_48e252_idx'),
        ),
        migrations.AddConstraint(
            model_name='artifactlink',
            constraint=models.UniqueConstraint(fields=('artifact', 'subject_type', 'subject_id', 'role', 'direction'), name='unique_artifact_link'),
        ),
    ]
