# Generated by Django 5.1.15 on 2026-09-11 00:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gate', models.CharField(choices=[('hazard_candidate', 'Hazard candidate'), ('exposure_enrichment', 'Exposure-enrichment candidate'), ('converter_candidate', 'Converter candidate'), ('vulnerability_candidate', 'Vulnerability candidate'), ('data_rights', 'Data-rights gate'), ('model_release', 'Model release'), ('platform_release', 'Platform release'), ('run_exception', 'Permitted run exception')], db_index=True, max_length=32)),
                ('decision', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='requested', max_length=16)),
                ('subject_type', models.CharField(max_length=64)),
                ('subject_id', models.UUIDField()),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True, help_text='Why the gate was cleared or refused.')),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='Artifact URIs and check results the decision rested on.')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_decided', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subject_type', 'subject_id', 'gate'], name='audit_appro_subject_6e5999_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_label', models.CharField(blank=True, help_text='Actor name captured at the time, so the record survives user deletion.', max_length=150)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('read', 'Read'), ('download', 'Downloaded'), ('upload', 'Uploaded'), ('publish', 'Published'), ('submit', 'Submitted'), ('cancel', 'Cancelled'), ('retry', 'Retried'), ('approve', 'Approved'), ('reject', 'Rejected'), ('override', 'Overrode a value'), ('configure', 'Changed configuration'), ('sign_in', 'Signed in'), ('sign_in_failed', 'Sign-in failed')], db_index=True, max_length=32)),
                ('subject_type', models.CharField(db_index=True, max_length=64)),
                ('subject_id', models.CharField(db_index=True, max_length=64)),
                ('subject_label', models.CharField(blank=True, max_length=255)),
                ('before_reference', models.JSONField(blank=True, null=True)),
                ('after_reference', models.JSONField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, help_text='Follows one run across Django, the workers and the engine adapters.', max_length=64)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null where the action was taken by a worker rather than a person.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subject_type', 'subject_id', '-created_at'], name='audit_audit_subject_49d3b6_idx'), models.Index(fields=['project', '-created_at'], name='audit_audit_project_af87a1_idx'), models.Index(fields=['actor', '-created_at'], name='audit_audit_actor_i_fb4253_idx')],
            },
        ),
    ]
