# Generated by Django 5.1.15 on 2026-09-11 00:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modelregistry', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExposureVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frozen_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=200)),
                ('version', models.PositiveIntegerField(default=1, help_text='Increments within a project; a correction never edits in place.')),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('validating', 'Validating'), ('validated', 'Validated'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=16)),
                ('oed_schema_version', models.CharField(blank=True, max_length=32)),
                ('source_description', models.TextField(blank=True, help_text='Where the portfolio came from and the extract date.')),
                ('cedant', models.CharField(blank=True, max_length=200)),
                ('valuation_date', models.DateField(blank=True, null=True)),
                ('run_currency', models.CharField(blank=True, max_length=3)),
                ('currency_conversion_evidence', models.JSONField(blank=True, default=dict, help_text='Rates, valuation date, source and direction used to normalise values.')),
                ('location_count', models.IntegerField(default=0)),
                ('account_count', models.IntegerField(default=0)),
                ('total_tiv', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('tiv_by_coverage', models.JSONField(blank=True, default=dict)),
                ('tiv_by_country', models.JSONField(blank=True, default=dict)),
                ('tiv_by_currency', models.JSONField(blank=True, default=dict)),
                ('validation_report', models.JSONField(blank=True, default=dict, help_text='Findings, counts and summaries from the last validation pass.')),
                ('supported_perspectives', models.JSONField(blank=True, default=list, help_text='Perspectives the supplied files actually support.')),
                ('unmodelled_subperils', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposure_versions', to='projects.project')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='exposure.exposureversion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrichmentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_count', models.IntegerField(default=0)),
                ('derived_count', models.IntegerField(default=0)),
                ('corroborated_count', models.IntegerField(default=0)),
                ('imputed_count', models.IntegerField(default=0)),
                ('override_count', models.IntegerField(default=0)),
                ('mean_confidence', models.FloatField(default=0.0)),
                ('missingness_profile', models.JSONField(blank=True, default=dict, help_text='Field completeness before enrichment, by count and by value.')),
                ('attribute_lineage', models.JSONField(blank=True, default=dict, help_text='Per-attribute evidence class distribution and rule versions.')),
                ('reconciliation', models.JSONField(blank=True, default=dict)),
                ('reconciled', models.BooleanField(default=False)),
                ('exceptions', models.JSONField(blank=True, default=list, help_text='Records that could not be enriched and the reason.')),
                ('output_checksum', models.CharField(blank=True, max_length=80)),
                ('assumption_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrichment_runs', to='modelregistry.assumptionset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('exposure_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrichment_runs', to='exposure.exposureversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttributeOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_reference', models.CharField(max_length=120)),
                ('attribute', models.CharField(max_length=64)),
                ('previous_value', models.CharField(blank=True, max_length=200)),
                ('previous_evidence', models.CharField(blank=True, max_length=32)),
                ('new_value', models.CharField(max_length=200)),
                ('rationale', models.TextField()),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribute_overrides_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('enrichment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='exposure.enrichmentrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['enrichment_run', 'location_reference'], name='exposure_at_enrichm_833974_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='exposureversion',
            index=models.Index(fields=['project', 'state'], name='exposure_ex_project_386342_idx'),
        ),
        migrations.AddConstraint(
            model_name='exposureversion',
            constraint=models.UniqueConstraint(fields=('project', 'name', 'version'), name='unique_exposure_version'),
        ),
        migrations.AddIndex(
            model_name='enrichmentrun',
            index=models.Index(fields=['exposure_version', '-created_at'], name='exposure_en_exposur_ae5727_idx'),
        ),
    ]
