# Generated by Django 5.1.15 on 2026-09-12 01:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
        ('exposure', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.CharField(help_text='The import profile that read this source, such as the Klapton Re geocoded policy extract.', max_length=120)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('source_checksum', models.CharField(db_index=True, max_length=80)),
                ('snapshot_date', models.DateField(blank=True, null=True)),
                ('schema_version', models.CharField(blank=True, max_length=80)),
                ('parser_version', models.CharField(blank=True, max_length=32)),
                ('cohort_rule_version', models.CharField(blank=True, max_length=32)),
                ('join_rule_version', models.CharField(blank=True, max_length=32)),
                ('state', models.CharField(choices=[('parsed', 'Parsed'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='parsed', max_length=16)),
                ('policy_row_count', models.IntegerField(default=0)),
                ('location_row_count', models.IntegerField(default=0)),
                ('findings', models.JSONField(blank=True, default=list, help_text='Type and required-value findings raised while parsing.')),
                ('join_report', models.JSONField(blank=True, default=dict)),
                ('cohort_profile', models.JSONField(blank=True, default=dict)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches_accepted', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='projects.project')),
                ('source_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='artifacts.artifact')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourcePolicyRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.IntegerField(help_text='The spreadsheet row, counting the header.')),
                ('policy_id', models.CharField(db_index=True, max_length=64)),
                ('business_id', models.CharField(db_index=True, max_length=64)),
                ('gross_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('risk_location_count', models.IntegerField(blank=True, null=True)),
                ('class_of_business', models.CharField(blank=True, max_length=120)),
                ('insured_country', models.CharField(blank=True, max_length=120)),
                ('values', models.JSONField(blank=True, default=dict)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_rows', to='exposure.importbatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='SourceRiskLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.IntegerField()),
                ('business_id', models.CharField(db_index=True, max_length=64)),
                ('location_number', models.IntegerField()),
                ('primary_location', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('precision', models.CharField(blank=True, max_length=32)),
                ('needs_review', models.BooleanField(default=False)),
                ('class_of_business', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('cohort', models.CharField(db_index=True, max_length=16)),
                ('cohort_reason', models.CharField(blank=True, max_length=200)),
                ('cohort_rule_version', models.CharField(blank=True, max_length=32)),
                ('review_state', models.CharField(choices=[('not_required', 'No review required'), ('pending', 'Awaiting review'), ('confirmed', 'Confirmed as located'), ('corrected', 'Corrected'), ('excluded', 'Excluded from modelling')], default='not_required', max_length=16)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('values', models.JSONField(blank=True, default=dict)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_rows', to='exposure.importbatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations_reviewed', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['business_id', 'location_number'],
            },
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['project', 'state', '-created_at'], name='exposure_im_project_1da7a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(fields=('project', 'source_checksum'), name='unique_import_per_source'),
        ),
        migrations.AddIndex(
            model_name='sourcepolicyrow',
            index=models.Index(fields=['batch', 'business_id'], name='exposure_so_batch_i_3ced4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcepolicyrow',
            constraint=models.UniqueConstraint(fields=('batch', 'policy_id'), name='unique_policy_per_batch'),
        ),
        migrations.AddIndex(
            model_name='sourcerisklocation',
            index=models.Index(fields=['batch', 'cohort'], name='exposure_so_batch_i_0b8402_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcerisklocation',
            index=models.Index(fields=['batch', 'review_state'], name='exposure_so_batch_i_cb7e95_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcerisklocation',
            constraint=models.UniqueConstraint(fields=('batch', 'business_id', 'location_number'), name='unique_location_per_batch'),
        ),
    ]
