# Generated by Django 5.1.15 on 2026-09-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposure', '0002_importbatch_sourcepolicyrow_sourcerisklocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposureversion',
            name='source_lineage',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='exposure_versions',
            field=models.ManyToManyField(blank=True, related_name='source_batches', to='exposure.exposureversion'),
        ),
        migrations.AddField(
            model_name='sourcerisklocation',
            name='cass_location_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
