"""Reshape the staging tables for the CASS intake template.

Written by hand rather than autogenerated, because the autodetector cannot tell
a rename from a drop-and-add and the difference matters: ``location_row_count``
becoming ``risk_row_count`` keeps its numbers, while ``join_report`` becoming
``intake_report`` deliberately does not -- a join report describes a
reconciliation the new format does not perform, so carrying its contents
forward under a new name would leave a batch claiming a report nobody produced.

The location reference changes from an integer to text, because OED makes
``LocNumber`` text. Existing values are whole numbers and cast cleanly.
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exposure", "0003_exposureversion_source_lineage_and_more"),
    ]

    operations = [
        # -- the batch -----------------------------------------------------
        migrations.RenameField(
            model_name="importbatch",
            old_name="location_row_count",
            new_name="risk_row_count",
        ),
        migrations.RemoveField(model_name="importbatch", name="join_rule_version"),
        migrations.RemoveField(model_name="importbatch", name="join_report"),
        migrations.AddField(
            model_name="importbatch",
            name="intake_report",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="importbatch",
            name="findings",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "Type, required-value and cross-sheet findings raised while "
                    "parsing."
                ),
            ),
        ),
        # -- policies ------------------------------------------------------
        migrations.RemoveConstraint(
            model_name="sourcepolicyrow", name="unique_policy_per_batch"
        ),
        migrations.RenameField(
            model_name="sourcepolicyrow", old_name="gross_limit", new_name="policy_tiv"
        ),
        migrations.RemoveField(model_name="sourcepolicyrow", name="risk_location_count"),
        migrations.RemoveField(model_name="sourcepolicyrow", name="insured_country"),
        migrations.RemoveField(model_name="sourcepolicyrow", name="class_of_business"),
        migrations.AddField(
            model_name="sourcepolicyrow",
            name="currency",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name="sourcepolicyrow",
            name="layer_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="sourcepolicyrow",
            constraint=models.UniqueConstraint(
                fields=("batch", "business_id", "policy_id", "layer_number"),
                name="unique_policy_layer_per_batch",
            ),
        ),
        # -- risks ---------------------------------------------------------
        migrations.AlterField(
            model_name="sourcerisklocation",
            name="location_number",
            field=models.CharField(max_length=64),
        ),
        migrations.RemoveField(model_name="sourcerisklocation", name="country"),
        migrations.AddField(
            model_name="sourcerisklocation",
            name="total_insured_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=22, null=True
            ),
        ),
        migrations.AddField(
            model_name="sourcerisklocation",
            name="currency",
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
