# Generated by Django 5.1.15 on 2026-09-13 16:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposure', '0007_enrichmentrun_baseline_weights'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frozen_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('from_currency', models.CharField(db_index=True, max_length=3)),
                ('to_currency', models.CharField(db_index=True, max_length=3)),
                ('rate', models.DecimalField(decimal_places=10, help_text='Units of the target currency that one unit of the source currency buys.', max_digits=24)),
                ('valuation_date', models.DateField(help_text='The date the quote is as at. A rate is evidence at a date, not a constant.')),
                ('source', models.CharField(help_text="The published quote this came from, such as a central bank's daily rate.", max_length=200)),
                ('reference', models.CharField(blank=True, help_text='Where a reviewer can check it: a URL, a document or an approval.', max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_rates_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['from_currency', 'to_currency', '-valuation_date'],
                'indexes': [models.Index(fields=['from_currency', 'to_currency', '-valuation_date'], name='exposure_cu_from_cu_1cbef5_idx')],
                'constraints': [models.UniqueConstraint(fields=('from_currency', 'to_currency', 'valuation_date', 'source'), name='unique_currency_rate')],
            },
        ),
    ]
