# Generated by Django 5.1.15 on 2026-09-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposure', '0008_currencyrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='reinsurance',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
