# Generated by Django 5.1.15 on 2026-09-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposure', '0009_importbatch_reinsurance'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='importbatch',
            name='unique_import_per_source',
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(
                fields=('project', 'source_checksum', 'parser_version', 'cohort_rule_version'),
                name='unique_import_per_source_and_rules',
            ),
        ),
    ]
