# Generated by Django 5.1.15 on 2026-09-13 17:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStandardVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frozen_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('standard', models.CharField(db_index=True, default='OED', help_text='The standard itself. OED is the only one CASS reads today.', max_length=16)),
                ('version', models.CharField(db_index=True, max_length=16)),
                ('state', models.CharField(choices=[('candidate', 'Candidate'), ('active', 'Active'), ('superseded', 'Superseded')], default='candidate', max_length=16)),
                ('source', models.CharField(help_text='Where the specification came from, such as the pinned ODS Tools release.', max_length=200)),
                ('reference_uri', models.CharField(blank=True, help_text='The registered specification artifact this record was read from.', max_length=500)),
                ('checksum', models.CharField(blank=True, max_length=80)),
                ('file_kinds', models.JSONField(blank=True, default=dict)),
                ('field_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('adopted_at', models.DateTimeField(blank=True, null=True)),
                ('adopted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_standards_adopted', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['standard', '-version'],
                'constraints': [models.UniqueConstraint(fields=('standard', 'version'), name='unique_data_standard_version')],
            },
        ),
    ]
