# Generated by Django 5.1.15 on 2026-09-11 00:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaPerilGrid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frozen_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('country_code', models.CharField(db_index=True, max_length=2)),
                ('version', models.CharField(help_text='Stable grid version. A change of geometry or mapping logic needs a new one.', max_length=32)),
                ('label', models.CharField(max_length=200)),
                ('base_resolution_deg', models.DecimalField(decimal_places=6, max_digits=8)),
                ('refined_resolution_deg', models.DecimalField(decimal_places=6, max_digits=8)),
                ('refinement_rule', models.TextField(help_text='How refined cells are selected, such as exposure density or hazard gradient.')),
                ('cell_count', models.BigIntegerField(default=0)),
                ('excludes_offshore', models.BooleanField(default=True, help_text="Indonesia's grid should avoid unnecessary calculation points over ocean.")),
                ('site_condition_source', models.CharField(blank=True, help_text='Provenance of Vs30, soil class and any basin parameters.', max_length=200)),
                ('site_condition_fallback', models.TextField(blank=True, help_text='Fallback hierarchy where site parameters are unavailable.')),
                ('border_policy', models.TextField(blank=True, help_text='Treatment of locations near national borders and coastlines.')),
                ('mapping_tolerance_km', models.DecimalField(decimal_places=2, default=0, help_text='Distance beyond which a location is reported rather than snapped.', max_digits=6)),
                ('publication_state', models.CharField(choices=[('draft', 'Draft'), ('candidate', 'Candidate awaiting approval'), ('approved', 'Approved'), ('published', 'Published'), ('superseded', 'Superseded'), ('withdrawn', 'Withdrawn')], default='draft', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='modelregistry.areaperilgrid')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['country_code', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssumptionSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frozen_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('country_code', models.CharField(db_index=True, max_length=2)),
                ('flavour', models.CharField(choices=[('baseline', 'Baseline'), ('more_robust', 'More robust'), ('more_vulnerable', 'More vulnerable')], max_length=20)),
                ('version', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=200)),
                ('segment', models.CharField(blank=True, help_text='Portfolio segment the set applies to, such as facultative commercial.', max_length=120)),
                ('rules', models.JSONField(default=dict)),
                ('provenance', models.TextField(blank=True, help_text='Where the priors come from and how they were calibrated.')),
                ('weighting_basis', models.CharField(choices=[('replacement_cost', 'Replacement cost'), ('floor_area', 'Floor area'), ('building_count', 'Building count')], default='replacement_cost', help_text='Section 8 prefers cost or area weighting over building counts for facultative risks.', max_length=32)),
                ('publication_state', models.CharField(choices=[('draft', 'Draft'), ('candidate', 'Candidate awaiting approval'), ('approved', 'Approved'), ('published', 'Published'), ('superseded', 'Superseded'), ('withdrawn', 'Withdrawn')], default='draft', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['country_code', 'flavour', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VulnerabilitySet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frozen_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('country_code', models.CharField(db_index=True, max_length=2)),
                ('version', models.CharField(max_length=32)),
                ('source', models.CharField(help_text='Provenance, such as GEM Global Vulnerability Model v2026.0.0.', max_length=200)),
                ('source_commit', models.CharField(blank=True, max_length=64)),
                ('taxonomy_generation', models.CharField(blank=True, help_text='Taxonomy release. Exposure and vulnerability generations must match.', max_length=32)),
                ('licence', models.CharField(blank=True, max_length=120)),
                ('licence_cleared', models.BooleanField(default=False, help_text='Whether commercial use has been confirmed in writing by the licensor.')),
                ('licence_note', models.TextField(blank=True)),
                ('function_count', models.IntegerField(default=0)),
                ('imts_used', models.JSONField(default=list, help_text='Distinct intensity measures the functions demand.')),
                ('coverage_components', models.JSONField(default=list, help_text='Structural, non-structural, contents or business interruption.')),
                ('damage_bin_count', models.IntegerField(default=0)),
                ('publication_state', models.CharField(choices=[('draft', 'Draft'), ('candidate', 'Candidate awaiting approval'), ('approved', 'Approved'), ('published', 'Published'), ('superseded', 'Superseded'), ('withdrawn', 'Withdrawn')], default='draft', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['country_code', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frozen_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('country_code', models.CharField(db_index=True, max_length=2)),
                ('peril', models.CharField(choices=[('QEQ', 'Earthquake shake')], default='QEQ', max_length=8)),
                ('version', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=200)),
                ('hazard_source_model', models.CharField(blank=True, max_length=200)),
                ('hazard_source_licence', models.CharField(blank=True, max_length=120)),
                ('openquake_version', models.CharField(blank=True, max_length=32)),
                ('oasis_version', models.CharField(blank=True, max_length=32)),
                ('converter_version', models.CharField(blank=True, max_length=32)),
                ('oed_schema_version', models.CharField(blank=True, max_length=32)),
                ('imts', models.JSONField(default=list, help_text='Intensity measures this model version produces.')),
                ('peril_scope', models.JSONField(default=dict, help_text='Sub-peril treatment: included, proxied, excluded or not_material, with rationale.')),
                ('known_limitations', models.TextField(blank=True)),
                ('unsupported_taxonomy_report', models.JSONField(blank=True, default=dict, help_text='Vulnerability classes and TIV share this version cannot model.')),
                ('is_research_prototype', models.BooleanField(default=True, help_text='Research prototypes may be run but not used for decisions.')),
                ('publication_state', models.CharField(choices=[('draft', 'Draft'), ('candidate', 'Candidate awaiting approval'), ('approved', 'Approved'), ('published', 'Published'), ('superseded', 'Superseded'), ('withdrawn', 'Withdrawn')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('validation_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='modelregistry.areaperilgrid')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='modelregistry.modelversion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vulnerability_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='modelregistry.vulnerabilityset')),
            ],
            options={
                'ordering': ['country_code', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='areaperilgrid',
            constraint=models.UniqueConstraint(fields=('country_code', 'version'), name='unique_grid_version'),
        ),
        migrations.AddConstraint(
            model_name='assumptionset',
            constraint=models.UniqueConstraint(fields=('country_code', 'flavour', 'version'), name='unique_assumption_set_version'),
        ),
        migrations.AddConstraint(
            model_name='vulnerabilityset',
            constraint=models.UniqueConstraint(fields=('country_code', 'version'), name='unique_vulnerability_version'),
        ),
        migrations.AddConstraint(
            model_name='modelversion',
            constraint=models.UniqueConstraint(fields=('country_code', 'peril', 'version'), name='unique_model_version'),
        ),
    ]
