[pytest]
DJANGO_SETTINGS_MODULE = kre.settings.test
python_files = test_*.py
testpaths = kre_api/tests packages/kre_core/tests packages/kre_oed/tests services
pythonpath = kre_api packages/kre_core packages/kre_oed services/converter services/keys adapters
addopts = -q --strict-markers
filterwarnings =
    error::DeprecationWarning:kre_.*
