[pytest]
DJANGO_SETTINGS_MODULE = cass.settings.test
python_files = test_*.py
testpaths = cass_api/tests packages/cass_core/tests packages/cass_oed/tests services adapters/tests
pythonpath = cass_api packages/cass_core packages/cass_oed services/converter services/keys adapters
addopts = -q --strict-markers
filterwarnings =
    error::DeprecationWarning:cass_.*
