# Generated by Django 5.1.15 on 2026-09-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='gate_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='run',
            name='gate_summary',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
