# Generated by Django 5.1.15 on 2026-09-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0004_analysisrun_assumption_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='mode',
            field=models.CharField(choices=[('geometry_only', 'Geometry only, no loss calculated'), ('technical', 'KRE-share technical loss'), ('research', 'Portfolio-loss research'), ('decision', 'Decision use')], db_index=True, default='technical', help_text='What this analysis is for, and therefore what its output may claim.', max_length=16),
        ),
    ]
