# Generated by Django 5.1.15 on 2026-09-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0005_analysisrun_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='currency_conversion',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
