# Generated by Django 5.1.15 on 2026-09-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0006_analysisrun_currency_conversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardrun',
            name='logic_tree_paths',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
