# Generated by Django 5.1.15 on 2026-09-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0007_hazardrun_logic_tree_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='stage_progress',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='stage_progress_label',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
