# Generated by Django 5.1.15 on 2026-09-17 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelregistry', '0015_domain_rebuild_and_intensity_bins'),
        ('runs', '0008_run_stage_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardrun',
            name='rebuild_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rebuild_runs', to='modelregistry.hazardset'),
        ),
    ]
