# Generated by Django 5.1.15 on 2026-09-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0009_hazardrun_rebuild_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='cover_terms',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='reinsurance_cover',
            field=models.CharField(choices=[('engine', 'As the engine applies it: every event in full, no annual limit'), ('contract_terms', 'Limited by contract terms: reinstatements and their premiums')], default='engine', help_text="How the reinsurance contracts' annual limits are read.", max_length=16),
        ),
    ]
